version: '3.9'
services:
  caddy:
    container_name: caddy
    image: caddy:2
    depends_on:
      - pds
    restart: unless-stopped
    ports:
      - "${CADDY_PUB_IPV4:-0.0.0.0}:80:80"
      - "[${CADDY_PUB_IPV6:-::}]:80:80"
      - "${CADDY_PUB_IPV4:-0.0.0.0}:443:443"
      - "[${CADDY_PUB_IPV6:-::}]:443:443"
    networks:
      - front
    volumes:
      - type: bind
        source: /pds/caddy/data
        target: /data
      - type: bind
        source: /pds/caddy/etc/caddy
        target: /etc/caddy
      - type: bind
        source: /pds/caddy/webroot
        target: /srv/webroot
  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/pds:0.4
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - front
    volumes:
      - type: bind
        source: /pds
        target: /pds
    env_file:
      - /pds/pds.env
  watchtower:
    container_name: watchtower
    image: ghcr.io/nicholas-fedor/watchtower:latest
    networks:
      - front
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "@midnight"
  gatekeeper:
    container_name: gatekeeper
    image: fatfingers23/pds_gatekeeper:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - front
    # This gives the container to the access to the PDS folder.
    # Source is the location on your server of that directory.
    volumes:
      - type: bind
        source: /pds
        target: /pds
    depends_on:
      - pds

networks:
  front:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 172.30.0.0/24
        - subnet: fd00:30::/64
