---
pds_directory: /pds
pds_webroot: /pds/caddy/webroot
pds_env_path: "{{ pds_directory }}/pds.env"

status_script_path: /usr/local/bin/generate-status.py
status_output_path: /pds/status.html
status_service_name: status-report
status_timer_name: status-report

pds_systemd_service: pds

# Feature toggles
status_run_once: false
pds_restart: false
